version: "3"
services:
  django_web:
    build: .
    restart: on-failure
    env_file:
      - ./.env
    command:
      - gunicorn --bind 0.0.0.0:8080 project.wsgi
      - python3 HTTP-Diff-Bot/manage.py makemigrations checkweb
      - python3 HTTP-Diff-Bot/manage.py migrate
    ports:
      - "8080:8080"
    depends_on:
      - nginx
  nginx:
    image: "nginx"
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./staticfiles:/static
      - ./mediafiles:/media
    ports:
      - "80:80"